# Generated by Django 5.0.4 on 2024-11-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0003_remove_booking_comment_remove_booking_guest_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name_plural": "Menu"},
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_item_image",
            field=models.ImageField(default="", upload_to="menu_images"),
        ),
    ]
